[INTERNAL] sap.ui.core TestRunner: Downport (copy) sources of TestRunner from UI5 CLI to legacy versions
This downports (copies) all TestRunner files from the current version of the UI5 CLI (commit: fca87ff15674e8ac18337bd822f2632eb81402d4) to 1.84.
Exception: Lines 382-387 of TestRunner.js have been kept from the original (since that's an IE11 workaround and 1.84 supports it).

Also Fixes: https://github.com/UI5/openui5/issues/4438

PS1: Copy
PS2-3: *no code changes
PS4: Remove "allow-scripts" sandbox setting (Downport)

SNOW: n/a
JIRA: CPOUI5FOUNDATION-1236
CR-Id: 002075125800002177582026
Change-Id: Ieb469f69b70aa14b52a9cf5e63eae382e32ebbcb